[Settings]
text_font_size = 16
text_font_color = "#ffffff"
capture_frequency = "非常慢 (5 秒)"
google_cloud_key_file_path = "/Users/menghao/Downloads/大學專題資料/googleAPI/manifest-surfer-400014-8bcc91f54c0b.json"
