[Settings]
text_font_size = 16
text_font_color = "#FFFFFF"
capture_frequency = "標準 (2 秒)"
google_cloud_key_file_path = "/Users/menghao/Downloads/大學專題資料/googleAPI/manifest-surfer-400014-aa2bec31738b.json"
